[workspace]
members = ["crates/aw-core", "crates/steam-helper", "src-tauri"]
resolver = "2"

[workspace.package]
version = "0.1.0-preview.12"
edition = "2024"
license = "LGPL-3.0-only"
rust-version = "1.88"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

[profile.dev]
debug = 1
incremental = true
